server:
  port: 8182
  host: 0.0.0.0
catalogs:
  - name: sqlite-catalog-demo
    type: jdbc
    uri: jdbc:sqlite:file:./catalog.db
    jdbc.schema-version: V1
    warehouse: ./data
  - name: rest-catalog-demo
    type: rest
    uri: http://localhost:8181
    warehouse: s3://warehouse/wh/
    io-impl: org.apache.iceberg.aws.s3.S3FileIO
    s3.endpoint: http://localhost:9000
    s3.access-key-id: admin
    s3.secret-access-key: password
    s3.region: us-east-1
    s3.path-style-access: true
