blank_issues_enabled: true
contact_links:
  - name: 💬 Slack Community
    url: https://go.nimtable.com/slack
    about: Join our Slack workspace for real-time help, discussions, and community support
