# Nimtable config file to be mounted into the Docker containers.
# See backend/config.yaml for more complete example

server:
  port: 8182
  host: 0.0.0.0
catalogs:
  - name: sqlite-catalog-demo
    type: jdbc
    uri: jdbc:sqlite:file:./catalog.db
    jdbc.schema-version: V1
    warehouse: ./data
