/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("CatalogAPIApi", () => {
  let instance: api.CatalogAPIApi
  beforeEach(function() {
    instance = new api.CatalogAPIApi(config)
  });

  test("cancelPlanning", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    const table: any = undefined
    const planId: any = undefined
    return expect(instance.cancelPlanning(prefix, namespace, table, planId, {})).resolves.toBe(null)
  })
  test("commitTransaction", () => {
    const body: api.CommitTransactionRequest = undefined
    const prefix: any = undefined
    return expect(instance.commitTransaction(body, prefix, {})).resolves.toBe(null)
  })
  test("createNamespace", () => {
    const body: api.CreateNamespaceRequest = undefined
    const prefix: any = undefined
    return expect(instance.createNamespace(body, prefix, {})).resolves.toBe(null)
  })
  test("createTable", () => {
    const body: api.CreateTableRequest = undefined
    const prefix: any = undefined
    const namespace: any = undefined
    const xIcebergAccessDelegation: any = undefined
    return expect(instance.createTable(body, prefix, namespace, xIcebergAccessDelegation, {})).resolves.toBe(null)
  })
  test("createView", () => {
    const body: api.CreateViewRequest = undefined
    const prefix: any = undefined
    const namespace: any = undefined
    return expect(instance.createView(body, prefix, namespace, {})).resolves.toBe(null)
  })
  test("dropNamespace", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    return expect(instance.dropNamespace(prefix, namespace, {})).resolves.toBe(null)
  })
  test("dropTable", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    const table: any = undefined
    const purgeRequested: any = undefined
    return expect(instance.dropTable(prefix, namespace, table, purgeRequested, {})).resolves.toBe(null)
  })
  test("dropView", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    const view: any = undefined
    return expect(instance.dropView(prefix, namespace, view, {})).resolves.toBe(null)
  })
  test("fetchPlanningResult", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    const table: any = undefined
    const planId: any = undefined
    return expect(instance.fetchPlanningResult(prefix, namespace, table, planId, {})).resolves.toBe(null)
  })
  test("fetchScanTasks", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    const table: any = undefined
    const body: api.FetchScanTasksRequest = undefined
    return expect(instance.fetchScanTasks(prefix, namespace, table, body, {})).resolves.toBe(null)
  })
  test("listNamespaces", () => {
    const prefix: any = undefined
    const pageToken: PageToken = undefined
    const pageSize: any = undefined
    const parent: any = undefined
    return expect(instance.listNamespaces(prefix, pageToken, pageSize, parent, {})).resolves.toBe(null)
  })
  test("listTables", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    const pageToken: PageToken = undefined
    const pageSize: any = undefined
    return expect(instance.listTables(prefix, namespace, pageToken, pageSize, {})).resolves.toBe(null)
  })
  test("listViews", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    const pageToken: PageToken = undefined
    const pageSize: any = undefined
    return expect(instance.listViews(prefix, namespace, pageToken, pageSize, {})).resolves.toBe(null)
  })
  test("loadCredentials", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    const table: any = undefined
    return expect(instance.loadCredentials(prefix, namespace, table, {})).resolves.toBe(null)
  })
  test("loadNamespaceMetadata", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    return expect(instance.loadNamespaceMetadata(prefix, namespace, {})).resolves.toBe(null)
  })
  test("loadTable", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    const table: any = undefined
    const xIcebergAccessDelegation: any = undefined
    const ifNoneMatch: any = undefined
    const snapshots: any = undefined
    return expect(instance.loadTable(prefix, namespace, table, xIcebergAccessDelegation, ifNoneMatch, snapshots, {})).resolves.toBe(null)
  })
  test("loadView", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    const view: any = undefined
    return expect(instance.loadView(prefix, namespace, view, {})).resolves.toBe(null)
  })
  test("namespaceExists", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    return expect(instance.namespaceExists(prefix, namespace, {})).resolves.toBe(null)
  })
  test("planTableScan", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    const table: any = undefined
    const body: api.PlanTableScanRequest = undefined
    return expect(instance.planTableScan(prefix, namespace, table, body, {})).resolves.toBe(null)
  })
  test("registerTable", () => {
    const body: api.RegisterTableRequest = undefined
    const prefix: any = undefined
    const namespace: any = undefined
    return expect(instance.registerTable(body, prefix, namespace, {})).resolves.toBe(null)
  })
  test("renameTable", () => {
    const body: api.RenameTableRequest = {
  "$ref" : "#/components/examples/RenameTableSameNamespace"
}
    const prefix: any = undefined
    return expect(instance.renameTable(body, prefix, {})).resolves.toBe(null)
  })
  test("renameView", () => {
    const body: api.RenameTableRequest = {
  "$ref" : "#/components/examples/RenameViewSameNamespace"
}
    const prefix: any = undefined
    return expect(instance.renameView(body, prefix, {})).resolves.toBe(null)
  })
  test("replaceView", () => {
    const body: api.CommitViewRequest = undefined
    const prefix: any = undefined
    const namespace: any = undefined
    const view: any = undefined
    return expect(instance.replaceView(body, prefix, namespace, view, {})).resolves.toBe(null)
  })
  test("reportMetrics", () => {
    const body: api.ReportMetricsRequest = undefined
    const prefix: any = undefined
    const namespace: any = undefined
    const table: any = undefined
    return expect(instance.reportMetrics(body, prefix, namespace, table, {})).resolves.toBe(null)
  })
  test("tableExists", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    const table: any = undefined
    return expect(instance.tableExists(prefix, namespace, table, {})).resolves.toBe(null)
  })
  test("updateProperties", () => {
    const body: api.UpdateNamespacePropertiesRequest = {
  "$ref" : "#/components/examples/UpdateAndRemoveNamespacePropertiesRequest"
}
    const prefix: any = undefined
    const namespace: any = undefined
    return expect(instance.updateProperties(body, prefix, namespace, {})).resolves.toBe(null)
  })
  test("updateTable", () => {
    const body: api.CommitTableRequest = undefined
    const prefix: any = undefined
    const namespace: any = undefined
    const table: any = undefined
    return expect(instance.updateTable(body, prefix, namespace, table, {})).resolves.toBe(null)
  })
  test("viewExists", () => {
    const prefix: any = undefined
    const namespace: any = undefined
    const view: any = undefined
    return expect(instance.viewExists(prefix, namespace, view, {})).resolves.toBe(null)
  })
})

describe("ConfigurationAPIApi", () => {
  let instance: api.ConfigurationAPIApi
  beforeEach(function() {
    instance = new api.ConfigurationAPIApi(config)
  });

  test("getConfig", () => {
    const warehouse: any = undefined
    return expect(instance.getConfig(warehouse, {})).resolves.toBe(null)
  })
})

describe("OAuth2APIApi", () => {
  let instance: api.OAuth2APIApi
  beforeEach(function() {
    instance = new api.OAuth2APIApi(config)
  });

  test("getToken", () => {
    return expect(instance.getToken({})).resolves.toBe(null)
  })
})

